version: '3.8'  # Specifies the Docker Compose file format version

services:  # Defines the container services section
  simulation:  # Name of your service
    build:  # Build configuration
      context: .  # Use current directory as build context
      dockerfile: Dockerfile  # Use this specific Dockerfile
    volumes:
      - ./:/app:rw  # Mount local directory to /app in container with read-write permissions
#      - /Users/zhishengxie/Library/CloudStorage/OneDrive-Personal/DataStorage/iqc_alpha:/app/alpha_onedrive:rw
#      - /Users/zhishengxie/Library/CloudStorage/OneDrive-Personal/DataStorage/iqc_alpha/pnl:/app/alpha_onedrive/pnl:rw
      - /e/OneDrive/DataStorage/iqc_alpha:/app/alpha_onedrive:rw
      - /e/OneDrive/DataStorage/iqc_alpha/pnl:/app/alpha_onedrive/pnl:rw
    working_dir: /app  # Set working directory inside container
    command: python -m main_simulation  # Command to run when container starts
    environment:  # Environment variables
      - PYTHONPATH=/app  # Add /app to Python's module search path
    # env_file:  # Optional: load environment variables from file
    #   - .env
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:rw
#      - /Users/zhishengxie/Library/CloudStorage/OneDrive-Personal/DataStorage/iqc_alpha:/app/alpha_onedrive:rw
      - /e/OneDrive/DataStorage/iqc_alpha:/app/alpha_onedrive:rw
    working_dir: /app
    command: python -m main_ui
    environment:
      - PYTHONPATH=/app
    ports:
      - "8501:8501"