version: 1
disable_existing_loggers:  True

formatters:
  standard:
    format: "%(asctime)s|%(funcName)s|%(levelname)s|%(message)s"
  error:
    format: "%(asctime)s|%(funcName)s|%(levelname)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout
    file_handler:
        class: src.utilities.log_cus_handler.CusQueueHandler
        level: DEBUG
        formatter: standard
        file_name_prefix: "log_"
        maxBytes: 10485760  # 10 MB
        backupCount: 10
        mode: "a"  # Append mode

root:
    level: WARNING
    handlers:
        - console
        - file_handler

loggers:
  data_pipeline:
    level: DEBUG
    handlers:
        - console
        - file_handler
    propagate: no